url: "https://sherow1982.github.io/sooq-alkuwait"
baseurl: "/sooq-alkuwait"
lang: ar
title: "سوق الكويت - متجر إلكتروني"
description: "تسوق اونلاين داخل الكويت - آلاف المنتجات مع توصيل سريع"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
